# worlds to load upon server startup, allowing for /wtp
# world specified in server.properties is already included
worlds:
  - example_world # no spaces!
  - another_example_world 

duel:
  # name of the world and region id for where duels may take place
  # region must reside in the world
  location: 'example_world:example_region' # **teleport flag must be outside of the region itself**
  pregameTime: 5 # how soon (in seconds) a game begins once both parties have made it into the arena
  cooldownTime: 20 # how soon (in seconds) another game may be initiated after a game has ended
  waitTime: 300 # how long a duel request lasts unfulfilled
  ingameTime: 180 # how long a duel may last
  # the honor that a player begins with (upon first login)
  initialHonor: 1400 # if a player has already logged in, use /honor to make changes
  # how great an honor difference required for and increase in order of magnitude of the change factor
  x: 400 # greater number makes for a greater range of honor values across all players
  k: 32 # change factor (also the maximum honor change occuring from a single duel)

opsDiscoverRegions: false # whether or not ops can discover regions

discoverableRegions:
  example_world: # the name of the world for the child regions
    example_region: # example-region is the id of the region to be defined as discoverable
      blockLocation: 41 119 17 # x y z of block to place once the region has been discovered
      block: 'minecraft:stone' # the type of block to be placed at blockLocation