name: Survivor
main: com.kaelkirk.Plugin
version: 1.0
depend: [WorldGuard]
# api-version: 1.13
commands:
  wtp:
    description: teleport to a world
    usage: /wtp [player] <world>
  duel:
    description: duel a player for honor
    usage: /duel <player>
